#!/usr/bin/env bash
# ============================================================================
# 00c-resolve-ids.sh
# ----------------------------------------------------------------------------
# Resolves the key record IDs for the Pyme demo in YOUR org and prints them
# as a table you can copy-paste to replace the hardcoded IDs in the runbooks.
#
# The runbooks (RUNBOOK_BLOCK*) reference specific record IDs and Storm URLs
# from the original engagement — those IDs will NOT match your org. Every
# script under demo-metadata/scripts/ resolves IDs dynamically by Name /
# DeveloperName / Code — but the click-by-click runbooks use literal URLs
# so a presenter can Ctrl+Click a link.
#
# Run this after 01→04 have populated the data. It queries your org for the
# canonical Names / Codes and prints:
#   - Instance URL of your org
#   - Every ID you need to build the pre-demo browser tabs
#   - Copy-paste-ready lightning URLs for each
#
# Usage:
#   ./00c-resolve-ids.sh <org-alias>
#   ORG_ALIAS=<alias> ./00c-resolve-ids.sh
#   ./00c-resolve-ids.sh <org-alias> --format=env    # env-var-style output
# ============================================================================

set -euo pipefail
export SF_DISABLE_LOG_FILE=true

ORG_ALIAS="${1:-${ORG_ALIAS:-}}"
FORMAT="table"
if [[ "$#" -ge 2 ]] && [[ "$2" == "--format=env" ]]; then FORMAT="env"; fi
if [[ -z "${ORG_ALIAS}" ]]; then
  echo "ERROR: pass the org alias as \$1 or export ORG_ALIAS=<alias>." >&2
  echo "Example: ./00c-resolve-ids.sh ins-alfa" >&2
  exit 1
fi

# Get instance URL from sf org display
INSTANCE_URL=$(sf org display --target-org "${ORG_ALIAS}" --json 2>/dev/null \
  | python3 -c 'import sys,json,re;raw=sys.stdin.read();clean=re.sub(r"\x1b\[[0-9;]*[a-zA-Z]","",raw);print(json.loads(clean)["result"]["instanceUrl"])')

if [[ -z "${INSTANCE_URL}" ]]; then
  echo "ERROR: could not get instanceUrl. Is '${ORG_ALIAS}' authenticated?" >&2
  exit 1
fi

# Helper: run SOQL, return first Id from records[]
q_id() {
  local q="$1"
  sf data query --target-org "${ORG_ALIAS}" --json --query "$q" 2>/dev/null \
    | python3 -c 'import sys,json,re;raw=sys.stdin.read();clean=re.sub(r"\x1b\[[0-9;]*[a-zA-Z]","",raw);r=json.loads(clean)["result"]["records"];print(r[0]["Id"] if r else "")'
}

# ----------------------------------------------------------------------------
# Resolve every ID the runbooks reference
# ----------------------------------------------------------------------------
BUNDLE_ID=$(q_id "SELECT Id FROM Product2 WHERE ProductCode='segPymeEmpresarial' LIMIT 1")
COV_RC_ID=$(q_id "SELECT Id FROM Product2 WHERE ProductCode='rcExtracontractual' LIMIT 1")
COV_INCENDIO_ID=$(q_id "SELECT Id FROM Product2 WHERE ProductCode='incendioAliados' LIMIT 1")
COV_EQUIPO_ID=$(q_id "SELECT Id FROM Product2 WHERE ProductCode='equipoElectronico' LIMIT 1")
COV_ROBO_ID=$(q_id "SELECT Id FROM Product2 WHERE ProductCode='roboAsalto' LIMIT 1")
COV_ROTURA_ID=$(q_id "SELECT Id FROM Product2 WHERE ProductCode='roturaMaquinaria' LIMIT 1")
COV_SUSTRACCION_ID=$(q_id "SELECT Id FROM Product2 WHERE ProductCode='sustraccionDinero' LIMIT 1")
CLASSIF_ID=$(q_id "SELECT Id FROM ProductClassification WHERE Name='Cobertura Pyme' LIMIT 1")
ATTR_SUMA_ID=$(q_id "SELECT Id FROM AttributeDefinition WHERE DeveloperName='Suma_Asegurada' LIMIT 1")

ACC_PANADERIA_ID=$(q_id "SELECT Id FROM Account WHERE Name LIKE 'Panader%La Espiga%' LIMIT 1")
POLICY_ID=$(q_id "SELECT Id FROM InsurancePolicy WHERE Name='POL-PYME-2026-0001' LIMIT 1")

IPC_INCENDIO_ID=$(q_id "SELECT Id FROM InsurancePolicyCoverage WHERE InsurancePolicyId='${POLICY_ID}' AND Name LIKE '%Incendio%' LIMIT 1")
IPC_EQUIPO_ID=$(q_id "SELECT Id FROM InsurancePolicyCoverage WHERE InsurancePolicyId='${POLICY_ID}' AND Name LIKE '%Equipo%' LIMIT 1")

CLAIM_ID=$(q_id "SELECT Id FROM Claim WHERE Name='SIN-PYME-2026-0001' LIMIT 1")
CLAIM_COVERAGE_ID=$(q_id "SELECT Id FROM ClaimCoverage WHERE ClaimId='${CLAIM_ID}' LIMIT 1")

DASH_PROD_ID=$(q_id "SELECT Id FROM Dashboard WHERE Title LIKE '%Producci%Pyme%' LIMIT 1")
DASH_RENEW_ID=$(q_id "SELECT Id FROM Dashboard WHERE Title LIKE '%Renovaciones%Pyme%' LIMIT 1")
DASH_CLAIMS_ID=$(q_id "SELECT Id FROM Dashboard WHERE Title LIKE '%Siniestralidad%Pyme%' LIMIT 1")

# ----------------------------------------------------------------------------
# Output
# ----------------------------------------------------------------------------
if [[ "${FORMAT}" == "env" ]]; then
  # Env-var format — sourceable in the current shell
  cat <<EOF
# Auto-generated by 00c-resolve-ids.sh for org '${ORG_ALIAS}'
# Source this file: source <(./demo-metadata/scripts/00c-resolve-ids.sh ${ORG_ALIAS} --format=env)
export INSTANCE_URL='${INSTANCE_URL}'
export BUNDLE_ID='${BUNDLE_ID}'
export COV_RC_ID='${COV_RC_ID}'
export COV_INCENDIO_ID='${COV_INCENDIO_ID}'
export COV_EQUIPO_ID='${COV_EQUIPO_ID}'
export COV_ROBO_ID='${COV_ROBO_ID}'
export COV_ROTURA_ID='${COV_ROTURA_ID}'
export COV_SUSTRACCION_ID='${COV_SUSTRACCION_ID}'
export CLASSIF_PYME_ID='${CLASSIF_ID}'
export ATTR_SUMA_ID='${ATTR_SUMA_ID}'
export ACC_PANADERIA_ID='${ACC_PANADERIA_ID}'
export POLICY_ID='${POLICY_ID}'
export IPC_INCENDIO_ID='${IPC_INCENDIO_ID}'
export IPC_EQUIPO_ID='${IPC_EQUIPO_ID}'
export CLAIM_ID='${CLAIM_ID}'
export CLAIM_COVERAGE_ID='${CLAIM_COVERAGE_ID}'
export DASH_PRODUCCION_ID='${DASH_PROD_ID}'
export DASH_RENOVACIONES_ID='${DASH_RENEW_ID}'
export DASH_SINIESTRALIDAD_ID='${DASH_CLAIMS_ID}'
EOF
else
  # Human-readable table + copy-paste-ready URLs
  cat <<EOF
==============================================================
 Resolved IDs for org '${ORG_ALIAS}'
 Instance URL: ${INSTANCE_URL}
==============================================================

Replace hardcoded values in the runbooks with these.

Block 1 — Product Catalog:
  Bundle (segPymeEmpresarial):    ${BUNDLE_ID}
    ${INSTANCE_URL}/lightning/r/Product2/${BUNDLE_ID}/view
  Coverage RC Extracontractual:   ${COV_RC_ID}
  Coverage Incendio y Aliados:    ${COV_INCENDIO_ID}
    ${INSTANCE_URL}/lightning/r/Product2/${COV_INCENDIO_ID}/view
  Coverage Equipo Electrónico:    ${COV_EQUIPO_ID}
  Coverage Robo y Asalto:         ${COV_ROBO_ID}
  Coverage Rotura Maquinaria:     ${COV_ROTURA_ID}
  Coverage Sustracción:           ${COV_SUSTRACCION_ID}
  Classification Cobertura Pyme:  ${CLASSIF_ID}
    ${INSTANCE_URL}/lightning/r/ProductClassification/${CLASSIF_ID}/view
  Attribute Suma Asegurada:       ${ATTR_SUMA_ID}

Block 2 — Policy Lifecycle:
  Account Panadería La Espiga:    ${ACC_PANADERIA_ID}
    ${INSTANCE_URL}/lightning/r/Account/${ACC_PANADERIA_ID}/view
  Policy POL-PYME-2026-0001:      ${POLICY_ID}
    ${INSTANCE_URL}/lightning/r/InsurancePolicy/${POLICY_ID}/view
  IPCoverage Incendio (POL):      ${IPC_INCENDIO_ID}
  IPCoverage Equipo (POL):        ${IPC_EQUIPO_ID}

Block 3 — Claims:
  Claim SIN-PYME-2026-0001:       ${CLAIM_ID}
    ${INSTANCE_URL}/lightning/r/Claim/${CLAIM_ID}/view
  ClaimCoverage (root of SIN):    ${CLAIM_COVERAGE_ID}

Block 6 — Dashboards:
  Dashboard Producción:           ${DASH_PROD_ID}
    ${INSTANCE_URL}/lightning/r/Dashboard/${DASH_PROD_ID}/view
  Dashboard Renovaciones:         ${DASH_RENEW_ID}
    ${INSTANCE_URL}/lightning/r/Dashboard/${DASH_RENEW_ID}/view
  Dashboard Siniestralidad:       ${DASH_CLAIMS_ID}
    ${INSTANCE_URL}/lightning/r/Dashboard/${DASH_CLAIMS_ID}/view

Tip: run with '--format=env' to get sourceable exports instead:
  source <(./demo-metadata/scripts/00c-resolve-ids.sh ${ORG_ALIAS} --format=env)

==============================================================
EOF
fi
